In [1]:
#import numpy package under the  name np
import numpy as np

In [20]:
#create a null vector of size 10
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# create a vector of number 10 to 49
arr1=np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
np.shape(arr1)

(40,)

In [10]:
arr1.dtype

dtype('int32')

In [16]:
print(np.version)


<module 'numpy.version' from 'C:\\Users\\abc\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [18]:
print(arr1.ndim)


1


In [25]:
#create a boolean array of all true values
np.ones((4,2), dtype=bool)


array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [5]:
arr1d =np.arange(20)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
arr2d= arr1d.reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
arr3d= np.arange(64).reshape(2,4,8)
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [23]:
#reverse a vector
np.arange(20,0,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [27]:
#create a null vector whose 5th value is 1 
array= np.zeros(10)
array[4]=1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [29]:
#create 3*3 identity matrix
matrix=np.identity(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
ar=np.array([1,2,3,4,5])
float_arr= ar.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [31]:
ar1= np.array([[1.,2.,3.],
              [4.,5.,6.]])
ar1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
ar2= np.array([[0.,4.,1.],
              [7.,2.,12.]])
ar2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
ar1 * ar2    #multiply array1 and array2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [36]:
#make the array by comparing two
ar1==ar2

array([[False, False, False],
       [False, False, False]])

In [50]:
array_odd=arr[1::2]
array_odd                      # extract all odd numbers

array([1, 3, 5, 7, 9])

In [59]:
array_odd *= -1
array_odd                  #replace odd array with -1

-1

In [75]:
arr=np.arange(10)
arr[5:9]= 12             # assigning value to index 5,6,7,8
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [81]:
ar1=np.ones((5,5))
ar1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
ar1[1:-1,1:-1]=0              #creating array whose 1 is at border and zero inside
ar1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr2d[1,1]=12              #turn 5 into 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [6]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
arr3d[0,:,:]= 64         #Convert all the values of 1st array to 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr2d= np.array([[0,1,2,3,4],[5,6,7,8,9]])   #Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
arr2d[0]

array([0, 1, 2, 3, 4])

In [22]:
arr2d[1,1]      #Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

6

In [38]:
arr2d[0:,2:3] #Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

array([[2],
       [7]])

In [42]:
array10= np.random.random((10,10))  #Create a 10x10 array with random values and find the minimum and maximum values
array10

array([[0.317649  , 0.52522048, 0.11113834, 0.86889114, 0.70980993,
        0.12280936, 0.95366038, 0.22709132, 0.01255331, 0.44259157],
       [0.2522098 , 0.8939137 , 0.64459892, 0.41959152, 0.22867404,
        0.88324259, 0.61558227, 0.74712314, 0.51658615, 0.37968669],
       [0.38895293, 0.90821328, 0.78562072, 0.12784373, 0.71893993,
        0.02665035, 0.90197365, 0.76682925, 0.58630507, 0.35746069],
       [0.04461983, 0.23124244, 0.04544767, 0.87809824, 0.88405339,
        0.67548267, 0.04077272, 0.69620748, 0.72523153, 0.94240276],
       [0.68909846, 0.34891635, 0.27067625, 0.97625586, 0.3639373 ,
        0.37742587, 0.92921001, 0.50317588, 0.7902121 , 0.33365837],
       [0.14764246, 0.43723191, 0.84153133, 0.67011814, 0.96787575,
        0.27395617, 0.71648069, 0.41829733, 0.14134363, 0.04069285],
       [0.4286451 , 0.44202785, 0.40827084, 0.01732837, 0.51450918,
        0.31366935, 0.60608997, 0.71834644, 0.47909807, 0.5812212 ],
       [0.1936229 , 0.16687282, 0.3557047

In [43]:
array10.min()

0.012553308704769006

In [44]:
array10.max()

0.9987520295832131

In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [46]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [53]:
print("common values between two arrays is:")    #Find the common items between a and b
np.intersect1d(a,b)      

common values between two arrays is:


array([2, 4])

In [65]:
np.where(a==b)  #Find the positions where elements of a and b match

(array([1, 3, 5, 7], dtype=int64),)

In [66]:
names= np.array(['bob','joe','will','joe','joe'])
names

array(['bob', 'joe', 'will', 'joe', 'joe'], dtype='<U4')

In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [74]:
data= np.random.randn(7,4)
data

array([[-1.06690821,  1.19362453,  0.9540428 ,  0.04179828],
       [ 0.70069708,  0.58290396,  0.82208194, -0.36374581],
       [-0.09697677,  0.11450356, -0.80145995,  1.0628614 ],
       [-0.35462275,  0.16056254,  0.39286407, -0.53785102],
       [ 2.07830313, -2.80868915, -0.44208564, -0.65654261],
       [ 2.14921735,  1.09582718, -1.02059686,  0.92458201],
       [ 0.05177895, -0.15594947, -0.5605392 , -1.04345596]])

In [102]:
data[(names!='will')]   #Find all the values from array data where the values from array names are not equal to Will

array([[-0.57821383,  1.19728689, -1.40399729,  0.37027011],
       [-0.14108343,  0.87644998, -0.50381168,  0.38191815],
       [ 1.01596848,  0.28919555,  2.29837178,  1.3744101 ],
       [ 0.74725228,  0.04101504, -0.60800951,  0.10489812],
       [-1.75358744, -2.00955296, -0.39619425, -0.15200702],
       [ 0.38587414, -1.15052647,  1.66549109,  0.22849538],
       [-1.34370932, -0.37872922,  0.97861398,  2.01405204]])

In [88]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names



array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [89]:
data = np.random.randn(7, 4)
data

array([[-0.57821383,  1.19728689, -1.40399729,  0.37027011],
       [-0.14108343,  0.87644998, -0.50381168,  0.38191815],
       [ 1.01596848,  0.28919555,  2.29837178,  1.3744101 ],
       [ 0.74725228,  0.04101504, -0.60800951,  0.10489812],
       [-1.75358744, -2.00955296, -0.39619425, -0.15200702],
       [ 0.38587414, -1.15052647,  1.66549109,  0.22849538],
       [-1.34370932, -0.37872922,  0.97861398,  2.01405204]])

In [100]:
data[(names!= 'Will')&(names!='Joe')]    #Find all the values from array data where the values from array names are not equal to Will and Joe

array([[-0.57821383,  1.19728689, -1.40399729,  0.37027011],
       [ 0.74725228,  0.04101504, -0.60800951,  0.10489812]])

In [11]:
arr2d=np.random.uniform(1,15, size= (5,3)) #Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
arr2d

array([[ 4.1403066 ,  3.8755482 ,  9.93264629],
       [11.89233204, 14.02447041,  9.04605779],
       [ 9.75246116, 10.20519976, 10.1677699 ],
       [12.20102514,  8.88948977, 10.69307174],
       [ 9.93549395, 14.41500638,  6.31156879]])

In [12]:
arr3d=np.random.uniform(1,16,size=(2,2,4))   #Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
arr3d

array([[[ 7.54400026,  4.17662946,  1.36623986,  5.772281  ],
        [ 4.30035942,  5.20282438,  6.75561947,  7.77429677]],

       [[ 1.0017724 , 14.03419796, 10.96647649, 14.3315091 ],
        [14.56554847, 12.36887992,  3.55578322, 14.48468929]]])

In [18]:
arr3d.swapaxes(1,2)      #Swap axes of the array you created in Question 32

array([[[ 7.54400026,  4.30035942],
        [ 4.17662946,  5.20282438],
        [ 1.36623986,  6.75561947],
        [ 5.772281  ,  7.77429677]],

       [[ 1.0017724 , 14.56554847],
        [14.03419796, 12.36887992],
        [10.96647649,  3.55578322],
        [14.3315091 , 14.48468929]]])

In [31]:
array=np.arange(10)
array=np.sqrt(array)
np.where(array<0.5,0,array)     #Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0



array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
arr1= np.random.randint(12)  #Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

arr1

10

In [33]:
arr2=np.random.randint(12)
arr2

1

In [34]:
np.maximum(arr1,arr2)

10

In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [44]:
X=np.unique(names)          #Find the unique names and sort them out!
X

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [45]:
np.sort(X)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [48]:
a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [49]:
b = np.array([5,6,7,8,9])
b

array([5, 6, 7, 8, 9])

In [58]:
np.delete(a,4)

array([1, 2, 3, 4])

In [62]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])       #Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray


array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [70]:
Result=np.delete(sampleArray,1,1)

In [66]:
newColumn

array([[10, 10, 10]])

In [71]:
np.insert(Result,1,newColumn,axis=1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [73]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])    
x


array([[1., 2., 3.],
       [4., 5., 6.]])

In [74]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [78]:
np.dot(x,y)       #Find the dot product of the above two matrix

array([[ 28.,  64.],
       [ 67., 181.]])

In [89]:
matrix=np.random.random((5,4))        #Generate a matrix of 20 random values and find its cumulative sum
matrix

array([[0.28057627, 0.35313834, 0.21740606, 0.33042382],
       [0.75551106, 0.66025522, 0.97533056, 0.5300336 ],
       [0.56025933, 0.15558304, 0.67536927, 0.54003304],
       [0.68579515, 0.18181464, 0.5785305 , 0.69437881],
       [0.57977448, 0.85056346, 0.69051189, 0.69505628]])

In [90]:
np.cumsum(matrix)

array([ 0.28057627,  0.63371461,  0.85112068,  1.1815445 ,  1.93705557,
        2.59731079,  3.57264135,  4.10267495,  4.66293428,  4.81851732,
        5.49388658,  6.03391962,  6.71971477,  6.90152941,  7.48005992,
        8.17443872,  8.75421321,  9.60477667, 10.29528856, 10.99034484])