In [2]:
import numpy as np

In [2]:
#Convert a 1D array to a 2D array with 2 rows

array1d=np.arange(10)
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
array2d=array1d.reshape(2,5)
array2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
#How to stack two arrays vertically?

a=np.array([0,1,2,3,4])
b= np.array([5,6,7,8,9])
c= np.array([1,1,1,1,1])
d= np.array([1,1,1,1,1])




In [14]:
array1= np.vstack((a,b,c,d))
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
array2= np.hstack((a,c,b,d))       #How to stack two arrays horizontally?
array2

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

In [25]:
arr=array2.reshape(2,10)
arr


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
array2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
ar1=array2d.flatten() #How to convert an array of arrays into a flat 1d array
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
array=np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
arr2d=array.reshape(3,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
arr=arr2d.ravel() #How to Convert higher dimension into one dimension?
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
arrX=arr.reshape(5,3) #Convert one dimension to higher dimension?
arrX

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
arr=np.random.random((5,5))
arr

array([[0.97586561, 0.51479583, 0.41955213, 0.41842373, 0.27400934],
       [0.25527287, 0.23764537, 0.88838341, 0.37991445, 0.52147564],
       [0.50229128, 0.59070646, 0.80489676, 0.50498647, 0.65279181],
       [0.85338774, 0.02294625, 0.24258873, 0.59527261, 0.45418281],
       [0.18617834, 0.10946471, 0.5599426 , 0.51693978, 0.07926455]])

In [14]:
a1=np.square(arr)        #Create 5x5 an array and find the square of an array
a1

array([[9.52313681e-01, 2.65014748e-01, 1.76023992e-01, 1.75078416e-01,
        7.50811191e-02],
       [6.51642391e-02, 5.64753197e-02, 7.89225075e-01, 1.44334991e-01,
        2.71936844e-01],
       [2.52296535e-01, 3.48934118e-01, 6.47858801e-01, 2.55011333e-01,
        4.26137141e-01],
       [7.28270635e-01, 5.26530346e-04, 5.88492914e-02, 3.54349484e-01,
        2.06282024e-01],
       [3.46623752e-02, 1.19825228e-02, 3.13535719e-01, 2.67226733e-01,
        6.28286963e-03]])

In [15]:
ar=np.random.random((5,6))
ar

array([[0.11284359, 0.84416466, 0.34021649, 0.55942802, 0.92502076,
        0.65740329],
       [0.74041983, 0.86157933, 0.02614344, 0.3088925 , 0.56096294,
        0.70355297],
       [0.02722529, 0.31504274, 0.11128536, 0.35607608, 0.72328669,
        0.63497275],
       [0.56984297, 0.92742529, 0.61142654, 0.06051804, 0.15942767,
        0.64856695],
       [0.27287554, 0.73219669, 0.54805778, 0.83446906, 0.11678022,
        0.55218691]])

In [16]:
np.mean(ar)      #Create 5x6 an array and find the mean.

0.49474301310574276

In [17]:
np.std(ar)        #standard deviation of "ar" array

0.2825367791769754

In [18]:
np.median(ar)        #mediam of "ar" array(question 8)

0.5601954775008295

In [19]:
np.transpose(ar)      #transpose of "ar" array (question 8)

array([[0.11284359, 0.74041983, 0.02722529, 0.56984297, 0.27287554],
       [0.84416466, 0.86157933, 0.31504274, 0.92742529, 0.73219669],
       [0.34021649, 0.02614344, 0.11128536, 0.61142654, 0.54805778],
       [0.55942802, 0.3088925 , 0.35607608, 0.06051804, 0.83446906],
       [0.92502076, 0.56096294, 0.72328669, 0.15942767, 0.11678022],
       [0.65740329, 0.70355297, 0.63497275, 0.64856695, 0.55218691]])

In [27]:
array= np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
np.trace(array)  #Create a 4x4 an array and find the sum of diagonal elements

30

In [22]:
np.linalg.det(array)   #Create a 4x4 an array and find the sum of diagonal elements

-2.9582283945787796e-30

In [24]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
p5=np.percentile(arr,5)    #Find the 5th and 95th percentile of an array
p5

0.45

In [26]:
p95=np.percentile(arr,95)
p95

8.549999999999999

In [30]:
#array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])
np.isnan(array)                                  #How to find if a given array has any null values

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])